const TOPBAR_HEIGHT = 48;

const ZOOM_INTENSITY = 0.001;
const MIN_ZOOM = 0.75;
const MAX_ZOOM = 5;

const BASE_STATE_RADIUS = 50;

export { TOPBAR_HEIGHT, ZOOM_INTENSITY, MIN_ZOOM, MAX_ZOOM, BASE_STATE_RADIUS };
