const TOPBAR_HEIGHT = 48;

const BACKGROUND_DOTS_GAP = 40;
const ZOOM_INTENSITY = 0.001;
const MIN_ZOOM = 0.75;
const MAX_ZOOM = 5;

const BASE_STATE_RADIUS = 50;
const INNER_DIAMETER_PADDING = 14;

export {
  TOPBAR_HEIGHT,
  BACKGROUND_DOTS_GAP,
  ZOOM_INTENSITY,
  MIN_ZOOM,
  MAX_ZOOM,
  BASE_STATE_RADIUS,
  INNER_DIAMETER_PADDING
};
